name: 'Solana Agave Version Updater'
description: 'Updates Agave validator deployment files based on Solana network requirements'

inputs:
  yaml-path:
    description: 'Path to the YAML file containing Solana version'
    required: true
  network:
    description: 'Solana network to check (mainnet, testnet, or devnet)'
    required: true
    default: 'testnet'
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.11'

outputs:
  min-version:
    description: 'The new required Solana version'
    value: ${{ steps.version-check.outputs.min-version }}
  current-version:
    description: 'The current deployed version'
    value: ${{ steps.version-check.outputs.current-version }}
  should-update:
    description: 'Whether the version needs to be updated'
    value: ${{ steps.version-check.outputs.should-update }}

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r ${{ github.action_path }}/src/action/requirements.txt

    - name: Run version checker
      shell: bash
      id: version-check
      env:
        INPUT_YAML_PATH: ${{ inputs.yaml-path }}
        INPUT_NETWORK: ${{ inputs.network }}
      run: python ${{ github.action_path }}/src/action/version_checker.py